M48
; DRILL file {KiCad 9.0.3} date 2025-09-17T15:29:18+0300
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-09-17T15:29:18+03:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.3
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.250
%
G90
G05
T1
X169.01Y-107.33
X169.01Y-128.67
X230.99Y-107.33
X230.99Y-128.67
M30
